%% Script for ElSpec_iqt usage for the 20061022 event

%% 1, Setting up the matlab-path
% Simply modify the path below to point to the directory where ELSPEC-2022
% is installed. That should be it.
addpath /home/bgu001/matlab/ELSPEC-recursive/ -end
addpath /home/bgu001/matlab/ELSPEC-master -end    

%% 2 Setup of parameters controlling ELSPEC

% Energy grid - between 10 ad 100 keV in 400 logarithmic/exponential steps
egrid = logspace(1,5,400);

% Data directories
% The paths to the directories with the ionospheric parameters and the
% power-profiles.
% fitdir = '/urdr/data/guisdap_processed_data/arc1/bjorn/2006-10-22_arc1_1@uhf';
fitdir = '/mnt/data/bjorn/EISCAT/Analysed/2006-10-22_arc1_4@uhf';
ppdir = fitdir;
% Flag for specifying which EISCAT-experiment it is
experiment = 'arc1';
% Altitude-limits.
hmax = 150;
hmin = 90;
% Time-limits
btime = [2006, 10, 22, 22,  0, 0];
etime = [2006, 10, 22, 23, 55, 0];
% Selection of which ionisation-profile method to use
ionomodel = 'Sergienko';
% and which type of continuity-integration-method to use
integtype = 'integrate';
% Time-resolution to use
tres = 'best';
% Maximum order of polynomial to try. The electron-flux is calculated as an
% the product of the energy with an exponential of an n-th order polynomial:
% Ie(E) = E*exp(p_n(E))
maxorder = 5;
% ninteg set to 5, here that only means that this is the number of
% time-steps to integrate for the initial condition
ninteg = 5;
% For additional settings see the help of ElSpec, ElSpec_iqt and ElSpec_qt
%%

% Pearson-type 6 statistics assumed
ErrType = 'l'; % L for Lorentzian.
Outname = 'ElSpec-Pulsating-Aurora-L-20061022-02.mat';
disp(Outname)
ElSpecQT_20061022_L = ElSpec_iqtcl('fitdir',fitdir,...
                                   'ppdir',ppdir,...
                                   'experiment',experiment,...
                                   'hmax',hmax,'hmin',hmin,...
                                   'btime',btime,'etime',etime,...
                                   'ionomodel',ionomodel,...
                                   'integtype',integtype,...
                                   'egrid',egrid,...
                                   'tres',tres,...
                                   'ErrType',ErrType,...
                                   'MaxOrder',maxorder,...
                                   'ninteg',ninteg,... 
                                   'Outfilename',Outname);

% ElSpecPlot(ElSpecQT_20061022_L)
ElSpecPlotIeNePpRes(ElSpecQT_20061022_L)
[fnm1,fnm2,fnm3] = fileparts(ElSpecQT_20061022_L.Outfilename); 
print('-depsc','-painters',[fnm2,'-QT-l-5']);
dstr = sprintf('Done with loop S i1: %i at %s',i1,datestr(now,'HH:MM:SS'));
disp(dstr)
close(gcf)
%% zoom-in on the 23:04 - 23:20 period
Outname = 'ElSpec-Pulsating-Aurora-L-20061022-03.mat';
btime = [2006, 10, 22, 23,  4, 0];
etime = [2006, 10, 22, 23, 20, 0];
nchunk = 16;
disp(Outname)
ElSpecQT_20061022_s = ElSpec_iqtcl('fitdir',fitdir,...
                                   'ppdir',ppdir,...
                                   'experiment',experiment,...
                                   'hmax',hmax,'hmin',hmin,...
                                   'btime',btime,'etime',etime,...
                                   'ionomodel',ionomodel,...
                                   'integtype',integtype,...
                                   'egrid',egrid,...
                                   'tres',tres,...
                                   'nchunk',nchunk,...
                                   'ErrType',ErrType,...
                                   'MaxOrder',maxorder,...
                                   'ninteg',ninteg,... 
                                   'Outfilename',Outname);

% ElSpecPlot(ElSpecQT_20061022_L)
ElSpecPlotIeNePpRes(ElSpecQT_20061022_s)
[fnm1,fnm2,fnm3] = fileparts(ElSpecQT_20061022_s.Outfilename); 
print('-dpng','-painters',[fnm2,'-QT-s']);
%% second zoom-in on the 23:04 - 23:20 period
Outname = 'ElSpec-Pulsating-Aurora-L-20061022-04.mat';
btime = [2006, 10, 22, 23,  4, 0];
etime = [2006, 10, 22, 23, 20, 0];
nchunk = 8;
disp(Outname)
ElSpecQT_20061022_s = ElSpec_iqtcl('fitdir',fitdir,...
                                   'ppdir',ppdir,...
                                   'experiment',experiment,...
                                   'hmax',hmax,'hmin',hmin,...
                                   'btime',btime,'etime',etime,...
                                   'ionomodel',ionomodel,...
                                   'integtype',integtype,...
                                   'egrid',egrid,...
                                   'tres',tres,...
                                   'nchunk',nchunk,...
                                   'ErrType',ErrType,...
                                   'MaxOrder',maxorder,...
                                   'ninteg',ninteg,... 
                                   'Outfilename',Outname);

% ElSpecPlot(ElSpecQT_20061022_L)
ElSpecPlotIeNePpRes(ElSpecQT_20061022_s)
[fnm1,fnm2,fnm3] = fileparts(ElSpecQT_20061022_s.Outfilename); 
print('-dpng','-painters',[fnm2,'-QT-s']);
%% second.5 zoom-in on the 23:04 - 23:20 period
Outname = 'ElSpec-Pulsating-Aurora-L-20061022-04b.mat';
btime = [2006, 10, 22, 23,  4, 2];
etime = [2006, 10, 22, 23, 20, 0];
nchunk = 8;
disp(Outname)
ElSpecQT_20061022_s = ElSpec_iqtcl('fitdir',fitdir,...
                                   'ppdir',ppdir,...
                                   'experiment',experiment,...
                                   'hmax',hmax,'hmin',hmin,...
                                   'btime',btime,'etime',etime,...
                                   'ionomodel',ionomodel,...
                                   'integtype',integtype,...
                                   'egrid',egrid,...
                                   'tres',tres,...
                                   'nchunk',nchunk,...
                                   'ErrType',ErrType,...
                                   'MaxOrder',maxorder,...
                                   'ninteg',ninteg,... 
                                   'Outfilename',Outname);

% ElSpecPlot(ElSpecQT_20061022_L)
ElSpecPlotIeNePpRes(ElSpecQT_20061022_s)
[fnm1,fnm2,fnm3] = fileparts(ElSpecQT_20061022_s.Outfilename); 
print('-dpng','-painters',[fnm2,'-QT-s']);

%% second.25 and second.75 zoom-ins on the 23:04 - 23:20 period
Outname = 'ElSpec-Pulsating-Aurora-L-20061022-04a.mat';
btime = [2006, 10, 22, 23,  4, 1];
etime = [2006, 10, 22, 23, 20, 0];
nchunk = 8;
disp(Outname)
ElSpecQT_20061022_s = ElSpec_iqtcl('fitdir',fitdir,...
                                   'ppdir',ppdir,...
                                   'experiment',experiment,...
                                   'hmax',hmax,'hmin',hmin,...
                                   'btime',btime,'etime',etime,...
                                   'ionomodel',ionomodel,...
                                   'integtype',integtype,...
                                   'egrid',egrid,...
                                   'tres',tres,...
                                   'nchunk',nchunk,...
                                   'ErrType',ErrType,...
                                   'MaxOrder',maxorder,...
                                   'ninteg',ninteg,... 
                                   'Outfilename',Outname);
Outname = 'ElSpec-Pulsating-Aurora-L-20061022-04c.mat';
btime = [2006, 10, 22, 23,  4, 3];
etime = [2006, 10, 22, 23, 20, 0];
nchunk = 8;
disp(Outname)
ElSpecQT_20061022_s = ElSpec_iqtcl('fitdir',fitdir,...
                                   'ppdir',ppdir,...
                                   'experiment',experiment,...
                                   'hmax',hmax,'hmin',hmin,...
                                   'btime',btime,'etime',etime,...
                                   'ionomodel',ionomodel,...
                                   'integtype',integtype,...
                                   'egrid',egrid,...
                                   'tres',tres,...
                                   'nchunk',nchunk,...
                                   'ErrType',ErrType,...
                                   'MaxOrder',maxorder,...
                                   'ninteg',ninteg,... 
                                   'Outfilename',Outname);

%% third zoom-in on the 23:04 - 23:20 period
Outname = 'ElSpec-Pulsating-Aurora-L-20061022-05.mat';
btime = [2006, 10, 22, 23,  4, 0];
etime = [2006, 10, 22, 23, 20, 0];
nchunk = 4;
disp(Outname)
ElSpecQT_20061022_s = ElSpec_iqtcl('fitdir',fitdir,...
                                   'ppdir',ppdir,...
                                   'experiment',experiment,...
                                   'hmax',hmax,'hmin',hmin,...
                                   'btime',btime,'etime',etime,...
                                   'ionomodel',ionomodel,...
                                   'integtype',integtype,...
                                   'egrid',egrid,...
                                   'tres',tres,...
                                   'nchunk',nchunk,...
                                   'ErrType',ErrType,...
                                   'MaxOrder',maxorder,...
                                   'ninteg',ninteg,... 
                                   'Outfilename',Outname);

% ElSpecPlot(ElSpecQT_20061022_L)
ElSpecPlotIeNePpRes(ElSpecQT_20061022_s)
[fnm1,fnm2,fnm3] = fileparts(ElSpecQT_20061022_s.Outfilename); 
print('-dpng','-painters',[fnm2,'-QT-s']);


%%
for i1 = numel(OUTLIERS):-1:1
  Outliers = OUTLIERS{i1};
  Outname = sprintf('ElSpec-iqtOutliers-L-5-%02i.mat',i1);
  disp(Outname)
  disp(Outliers)
  ElSpecQT_iqtOutliers_L5{i1} = ElSpec_iqt('fitdir',fitdir,...
                                       'ppdir',ppdir,...
                                       'experiment',experiment,...
                                       'hmax',hmax,'hmin',hmin,...
                                       'btime',btime,'etime',etime,...
                                       'ionomodel',ionomodel,...
                                       'integtype',integtype,...
                                       'egrid',egrid,...
                                       'tres',tres,...
                                       'ErrType',ErrType,...
                                       'MaxOrder',maxorder,...
                                       'ninteg',ninteg,...
                                        'Outliers',Outliers,...
                                       'Outfilename',Outname);
  ElSpecPlot(ElSpecQT_iqtOutliers_L5{i1})
  [fnm1,fnm2,fnm3] = fileparts(ElSpecQT_iqtOutliers_L5{i1}.Outfilename) ;
  print('-depsc','-vector',[fnm2,'-IQT-l-5']);
  dstr = sprintf('Done with loop S i1: %i at %s',i1,datestr(now,'HH:MM:SS'));
  disp(dstr)
  close(gcf)
  
end
%% Two modified plotting-functions
% In addition to ElSpecPlot, ElSpecPlot2 and ElSpecPlotSmall 2 new
% plotting-functions are added:
fig1 = figure;
ElSpecPlotIeNePpRes(ElSpecQT_iqtOutliers_L5{2},fig1.Number)
fig2 = figure;
ElSpecPlotRes(ElSpecQT_iqtOutliers_L5{2},fig2.Number)
ElSpecPlotIeNePpRes(ElSpecQT_iqtOutliers_L5{2})
ph = ElSpecPlotTres(ElSpecQT_iqtOutliers_L5{4});
set(ph,'color','r','linestyle','--','marker','.')
